import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Loader2, Sparkles, BookCheck, Copy } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useOrg } from "@/contexts/OrgContext";
import { useToast } from "@/hooks/use-toast";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSaved: () => void;
}

interface Fact {
  id: string;
  title: string;
  statement_text: string;
  category: string | null;
  status: string | null;
}

const SCENARIOS = ["Misinformation", "Support Issue", "Scam Warning", "Outage Update", "Regulatory Rumor", "Executive Rumor", "Fee Dispute", "Security Incident"];
const TONES = ["professional", "empathetic", "authoritative", "neutral", "urgent"];
const PLATFORMS = [
  { value: "short", label: "X (short — under 280 chars)" },
  { value: "general", label: "General purpose" },
  { value: "long", label: "Long form (email, blog)" },
];

export default function AutoGenerateDialog({ open, onOpenChange, onSaved }: AutoGenerateDialogProps) {
  const { currentOrg } = useOrg();
  const { toast } = useToast();
  const [facts, setFacts] = useState<Fact[]>([]);
  const [selectedFacts, setSelectedFacts] = useState<Set<string>>(new Set());
  const [scenario, setScenario] = useState("");
  const [tone, setTone] = useState("professional");
  const [platform, setPlatform] = useState("general");
  const [additionalContext, setAdditionalContext] = useState("");
  const [generating, setGenerating] = useState(false);
  const [generatedText, setGeneratedText] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!open || !currentOrg) return;
    setGeneratedText("");
    setSelectedFacts(new Set());
    setAdditionalContext("");
    setScenario("");

    supabase
      .from("approved_facts")
      .select("id, title, statement_text, category, status")
      .eq("org_id", currentOrg.id)
      .eq("status", "active")
      .order("title")
      .limit(100)
      .then(({ data }) => setFacts(data || []));
  }, [open, currentOrg]);

  const toggleFact = (id: string) => {
    setSelectedFacts(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const handleGenerate = async () => {
    if (!currentOrg || !scenario) return;
    setGenerating(true);
    setGeneratedText("");

    const chosenFacts = facts.filter(f => selectedFacts.has(f.id));
    const factsText = chosenFacts.length > 0
      ? chosenFacts.map((f, i) => `FACT ${i + 1} (${f.category || "General"}): "${f.statement_text}"`).join("\n")
      : "No specific facts selected — generate a general template structure.";

    try {
      const { data, error } = await supabase.functions.invoke("strict-respond", {
        body: {
          input_text: `Generate a response template for scenario: ${scenario}. ${additionalContext ? `Additional context: ${additionalContext}` : ""}`,
          platform,
          intent: scenario.toLowerCase().replace(/\s+/g, "_"),
          org_id: currentOrg.id,
          mode: "template_generate",
          tone,
          facts_context: factsText,
        },
      });

      if (error) throw new Error(error.message);
      if (data?.error) throw new Error(data.error);

      const output = data?.message || data?.output_text || "Template generation failed — try adjusting your inputs.";
      setGeneratedText(output);
    } catch (err: any) {
      toast({ title: "Generation failed", description: err.message, variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  const handleSaveAsTemplate = async () => {
    if (!currentOrg || !generatedText) return;
    setSaving(true);
    try {
      const { error } = await supabase.from("approved_templates").insert({
        org_id: currentOrg.id,
        name: `${scenario} — ${tone} (auto-generated)`,
        template_text: generatedText,
        scenario_type: scenario,
        tone,
        platform_length: platform,
        status: "draft",
      });
      if (error) throw error;
      toast({ title: "Template saved as draft" });
      onSaved();
      onOpenChange(false);
    } catch (err: any) {
      toast({ title: "Error", description: err.message, variant: "destructive" });
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl bg-card border-border max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-foreground flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" /> Auto-Generate Template
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-5 mt-2">
          {/* Configuration */}
          <div className="grid grid-cols-3 gap-3">
            <div className="space-y-2">
              <Label>Scenario *</Label>
              <Select value={scenario} onValueChange={setScenario}>
                <SelectTrigger className="bg-muted border-border"><SelectValue placeholder="Select..." /></SelectTrigger>
                <SelectContent>
                  {SCENARIOS.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Tone</Label>
              <Select value={tone} onValueChange={setTone}>
                <SelectTrigger className="bg-muted border-border"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {TONES.map(t => <SelectItem key={t} value={t} className="capitalize">{t}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Platform</Label>
              <Select value={platform} onValueChange={setPlatform}>
                <SelectTrigger className="bg-muted border-border"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {PLATFORMS.map(p => <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Fact Selection */}
          <div className="space-y-2">
            <Label className="flex items-center gap-1.5">
              <BookCheck className="h-3.5 w-3.5 text-primary" /> Include Approved Facts
            </Label>
            <p className="text-[11px] text-muted-foreground">Select facts to weave into the generated template</p>
            <div className="space-y-1.5 max-h-40 overflow-y-auto rounded-lg border border-border p-2">
              {facts.length === 0 ? (
                <p className="text-xs text-muted-foreground text-center py-3">No active facts. Add facts in the Approved Facts section first.</p>
              ) : (
                facts.map(f => (
                  <label key={f.id} className={`flex items-start gap-2 p-2 rounded-md cursor-pointer hover:bg-muted/50 transition-colors ${selectedFacts.has(f.id) ? "bg-primary/5" : ""}`}>
                    <Checkbox
                      checked={selectedFacts.has(f.id)}
                      onCheckedChange={() => toggleFact(f.id)}
                      className="mt-0.5"
                    />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-1.5">
                        <span className="text-xs font-medium text-foreground">{f.title}</span>
                        {f.category && <Badge variant="secondary" className="text-[9px]">{f.category}</Badge>}
                      </div>
                      <p className="text-[11px] text-muted-foreground line-clamp-1 mt-0.5">{f.statement_text}</p>
                    </div>
                  </label>
                ))
              )}
            </div>
            {selectedFacts.size > 0 && (
              <p className="text-[11px] text-primary">{selectedFacts.size} fact{selectedFacts.size !== 1 ? "s" : ""} selected</p>
            )}
          </div>

          {/* Additional Context */}
          <div className="space-y-2">
            <Label>Additional Context (optional)</Label>
            <Textarea
              value={additionalContext}
              onChange={e => setAdditionalContext(e.target.value)}
              placeholder="Any extra context, specific angles to address, or instructions for the template..."
              className="bg-muted border-border min-h-[60px]"
            />
          </div>

          <Button onClick={handleGenerate} disabled={generating || !scenario} className="w-full">
            {generating ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Sparkles className="h-4 w-4 mr-2" />}
            {generating ? "Generating..." : "Generate Template"}
          </Button>

          {/* Generated Output */}
          {generatedText && (
            <div className="space-y-3 border-t border-border pt-4">
              <div className="flex items-center justify-between">
                <Label className="text-foreground">Generated Template</Label>
                <Button size="sm" variant="ghost" onClick={() => { navigator.clipboard.writeText(generatedText); toast({ title: "Copied" }); }}>
                  <Copy className="h-3.5 w-3.5 mr-1" /> Copy
                </Button>
              </div>
              <Textarea
                value={generatedText}
                onChange={e => setGeneratedText(e.target.value)}
                className="bg-muted border-border font-mono text-xs min-h-[120px]"
              />
              <p className="text-[10px] text-muted-foreground">You can edit the text above before saving. Use {"{FACT_1}"}, {"{LINK_1}"} as placeholders.</p>
              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => onOpenChange(false)}>Discard</Button>
                <Button onClick={handleSaveAsTemplate} disabled={saving}>
                  {saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
                  Save as Draft Template
                </Button>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
