// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Don't crash the app — let the UI handle missing config gracefully
const missingConfig = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
if (missingConfig) {
  console.error(
    '[SentiWatch] Missing Supabase environment variables.\n' +
    'Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment.\n' +
    'In Lovable: Project Settings → Environment Variables.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabaseInstance: ReturnType<typeof createClient<Database>>;

if (missingConfig) {
  // Stub client — won't work but won't crash the app either
  // The UI will show a configuration error banner
  supabaseInstance = {
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { /* noop */ } } } }),
      signInWithPassword: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.' } }),
      signUp: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured.' } }),
      signOut: () => Promise.resolve({ error: null }),
      resetPasswordForEmail: () => Promise.resolve({ data: { /* noop */ }, error: null }),
    },
    from: () => ({ select: () => ({ eq: () => ({ single: () => Promise.resolve({ data: null, error: null }), maybeSingle: () => Promise.resolve({ data: null, error: null }) }) }), insert: () => ({ select: () => ({ single: () => Promise.resolve({ data: null, error: null }) }) }) }),
    rpc: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured.' } }),
    functions: { invoke: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured.' } }) },
    channel: () => ({ on: () => ({ subscribe: () => { /* noop */ } }) }),
    removeChannel: () => { /* noop */ },
  } as unknown;
} else {
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const supabase = supabaseInstance;
export const isSupabaseConfigured = !missingConfig;
